version: '3.4'
services:
  iam:
    container_name: iam-dbg
    build:
      target: dev
      args:
        - BUILD_ENV=Debug
    volumes:
      - ../netcore-compose-test/src/IAM:/build/src/IAM
      - ../netcore-compose-test/.paket:/build/.paket

  web:
    container_name: web-dbg
    build:
      target: dev
      args:
        - BUILD_ENV=Debug
    volumes:
      - ../netcore-compose-test/src/GiraffeWeb:/build/src/GiraffeWeb
      - ../netcore-compose-test/.paket:/build/.paket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    container_name: db-dbg
    ports:
      - 5432:5432
