version: '3.4'
services:
  iam:
    image: makewise/iam:latest
    build:
      context: ./netcore-compose-test/
      dockerfile: ../netcore-compose-test/src/IAM/Dockerfile
    ports:
      - 5050:5050
  web:
    image: makewise/web:latest
    build:
      context: ../netcore-compose-test/
      dockerfile: ../netcore-compose-test/src/GiraffeWeb/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - /var/lib/postgresql/data
