version: '3.4'
services:
  iam:
    restart: always
    build:
      target: final
      args:
        - BUILD_ENV=Production

  web:
    restart: always
    build:
      target: final
      args:
        - BUILD_ENV=Production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
